# when a PR is merged in main branch - create a release PR and when that is merged - publish the package

name: Publish
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  push:
    branches:
      - 'main'

# prevent multiple publish jobs from running at the same time
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v3
      # setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      # setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      # install node modules
      - run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
